site_name: serde-dataclass
site_description: Documentation for serde-dataclass
theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.top
    - search.suggest
    - content.code.copy
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
  - Custom Types: custom-types.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: xcode
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css